### ISSUE TITLE
Available to enjoy for XX hours/ This concert has ended

### ISSUE THREAD

**Issue by elesbok** [IDAGIO/product-requirements#15]
On the Concert Preview, upcoming and currently available concerts are "available to enjoy for 24h".

Since we're moving to a per-concert configuration of availability, this '24h' should be turned into a  specific date and time hence: **Available to enjoy until availabilityEnd**

As a result, switching to "This concert has ended" state should only happen **after the availabilityEnd** date and time.

**Comment by sdvig** [comment]
@elesbok you are explaining here about the **what** and **how** (implementation).

**what**: we want the **concert availability** to be derived from the **tickets sales end** (that will be configured manually).
that is possible.

But why is this requirement that it should be always multiple of 24? I think it should be taken in account when the person enters the tickets sales end date. Otherwise it won't be necessarily correct.

**Comment by elesbok** [comment]
@sdvig edited the description here, as per our discussion yesterday

**Comment by sdvig** [comment]
@elesbok if I understand you correct we are talking about this line:
![Screenshot 2020-06-24 at 17 12 27](https://user-images.githubusercontent.com/110833/85582693-edf8fe80-b63d-11ea-8e72-542dc5ffdeed.png)
And I think we only have it on the Concert Preview, and not on the Concert page (?)

**Comment by elesbok** [comment]
@sdvig you are correct! Will edit the description
